Repository whyphi/portal, pull requests merged in 2024-07, with the labels that each got.

#130 feat: Implement GitHub Release Automation
  .github/release.yml
Labels: feature

#133 Fix/add date and location fields
  app/admin/rush/layout.tsx
  app/admin/rush/page.tsx
  components/admin/rush/CreateDrawer.tsx
  components/admin/rush/EventModal.tsx
  components/admin/rush/SettingsModal.tsx
  types/admin/events.ts
  utils/date.ts
Labels: fix, improvement

#134 Feat/enable rush event cover image
  app/admin/rush/page.tsx
  components/admin/rush/CreateDrawer.tsx
  components/admin/rush/EventModal.tsx
  components/admin/rush/Image/CanvasPreview.tsx
  components/admin/rush/Image/CropImage.tsx
  package-lock.json
  package.json
  types/admin/events.ts
  utils/useDebounceEffect.tsx
Labels: feature, improvement

#135 Fix/rush events UI polish
  app/admin/rush/[eventId]/page.tsx
  app/admin/rush/page.tsx
  components/admin/rush/CreateDrawer.tsx
  components/admin/rush/Image/CropImage.tsx
  types/admin/events.ts
Labels: fix
