Repository whyphi/portal, pull requests merged in 2024-08, with the labels that each got.

#136 feat: create update account settings page
  app/admin/account-settings/layout.tsx
  app/admin/account-settings/page.tsx
  app/contexts/AuthContext.tsx
  components/admin/NavSidebar.tsx
  types/admin/account-settings/member.ts
Labels: feature

#137 Feat/rush analytics
  app/admin/listing/[listingId]/insights/page.tsx
  app/admin/listing/[listingId]/page.tsx
  app/admin/rush/[categoryId]/[eventId]/page.tsx
  app/admin/rush/[categoryId]/analytics/layout.tsx
  app/admin/rush/[categoryId]/analytics/page.tsx
  app/admin/rush/page.tsx
  components/admin/listing/ApplicantPage.tsx
  components/admin/rush/Image/CropImage.tsx
  package-lock.json
  package.json
  tailwind.config.ts
  types/admin/events.ts
Labels: feature

#138 feat: Create Family Tree Component
  app/admin/family-tree/layout.tsx
  app/admin/family-tree/page.tsx
  components/admin/NavSidebar.tsx
  package-lock.json
  package.json
Labels: feature

#142 Feat/analytics detail view
  app/admin/listing/[listingId]/insights/page.tsx
  app/admin/rush/[categoryId]/[eventId]/page.tsx
  app/admin/rush/[categoryId]/analytics/page.tsx
  app/admin/rush/page.tsx
  components/admin/listing/insights/SummaryCard.tsx
  types/admin/events.ts
  utils/getBaseURL.ts
Labels: feature, improvement

#144 fixed endpoint
  app/admin/rush/[categoryId]/analytics/page.tsx
Labels: bug

#146 adjusted end of base url
  utils/getBaseURL.ts
Labels: bug

#149 Merge: `2.0.1`
  app/admin/rush/page.tsx
  components/admin/rush/EventModal.tsx
  components/admin/rush/Image/CropImage.tsx
  components/admin/rush/Image/ImagePlaceholder.tsx
  types/admin/events.ts
  utils/getBaseURL.ts
Labels: fix

#150 Release: `2.0.1`
  app/admin/rush/page.tsx
  components/admin/rush/EventModal.tsx
  components/admin/rush/Image/CropImage.tsx
  components/admin/rush/Image/ImagePlaceholder.tsx
  types/admin/events.ts
  utils/getBaseURL.ts
Labels: release
